namespace GameData
{
    public enum Stance { AGRESSIVE, DEFENSIVE, AGILE, CAUTIOUS, TRICKY }
    public enum AbilityEffect { NONE, HEAL, UPATK, UPDEF, UPSPEED, DOWNATK, DOWNDEF, DOWNSPEED, STANCECHANGE, APPLYSTATUS, CURESTATUS }
    public enum AbilityType { ACTIVE, PASSIVE }

    public enum AbilityTarget { SELF, ONEENEMY, ONEALLY, ALLENEMIES, ALLALLIES, ALL }

    public enum Status { NONE, BURNED, POISONED, PARALYZED, FROZEN, ASLEEP }

    public enum Stats { ATK, DEF, SPEED, LUCK }

    public enum PassiveEffects { UPATK, UPATKONSTATUS, UPDEF, UPSPEED, DOWNATK, DOWNDEF, DOWNSPEED, ADDTURN, SKIPTURN, APPLYSTATUS }

    public enum PassiveExecutionTime { BATTLESTART, TURNSTART, TURNEND, ONHIT, ONHURT, OUTSIDEBATTLE, ONDEATH, ONKILL, ONSTANCECHANGE, ONSTATUSCHANGE }
}
