namespace GameData
{
    public enum Stance { AGRESSIVE, DEFFENSIVE, AGILE, CAUTIOUS, TRICKY }
    public enum AbilityEffect { NONE, HEAL, UPATK, UPDEF, UPSPEED, DOWNATK, DOWNDEF, DOWNSPEED, STANCECHANGE, APPLYBURN, APPLYPARA, APPLYPOISON, APPLYFRZ, APPLYSLP, CURESTATUS }
    public enum AbilityType { ACTIVE, PASSIVE }

    public enum AbilityTarget { SELF, ONEENEMY, ONEALLY, ALLENEMIES, ALLALLIES, ALL }

    public enum Status { NONE, BURNED, POISONED, PARALYZED, FROZEN, ASLEEP }

    public enum Stats { ATK, DEF, SPEED, LUCK }

    public enum PassiveEffects { UPATK, UPDEF, UPSPEED, DOWNATK, DOWNDEF, DOWNSPEED, ADDTURN, SKIPTURN, APPLYBURN, APPLYPARA, APPLYPOISON, APPLYFRZ, APPLYSLP }

    public enum PassiveExecutionTime { BATTLESTART, TURNSTART, TURNEND, ONHIT, ONHURT, OUTSIDEBATTLE, ONDEATH, ONKILL }
}
